#!/usr/bin/env python
# vim: ai ts=4 sts=4 et sw=4

from django.conf.urls.defaults import *
import ubuzima.views as views

urlpatterns = patterns('',
    url(r'^', views.index),
    url(r'^reporter/(?P<pk>\d+)$', views.by_reporter),
    url(r'^patient/(?P<pk>\d+)$', views.by_patient),
    url(r'^type/(?P<pk>\d+)$', views.by_type),
    url(r'^alerts$', views.view_alerts),
    url(r'^triggers$', views.triggers),
    url(r'^trigger/(?P<pk>\d+)$', views.trigger),
    url(r'^reminders$', views.view_reminders),
    url(r'^reminders/type/(?P<pk>\d+)$', views.remlog_by_type),
    url(r'^report/(?P<pk>\d+)$', views.view_report),
    url(r'^stats$', views.view_stats),
    url(r'^stats/csv$', views.view_stats_csv),
    url(r'^stats/reports/csv$', views.view_stats_reports_csv),
    url(r'^indicator/(?P<indic>\d+)/(?P<format>html|csv)$', views.view_indicator),
    url(r'^important/(?P<format>\w+)/(?P<dat>\w+)$',
        views.important_data),
    url(r'^stats/anc$',
        views.view_anc),
    url(r'^stats/anc/(?P<format>\w+)/(?P<dat>\w+)$',
        views.anc_stats),
    url(r'^stats/chihe$', views.view_chihe),
    url(r'^stats/chihe/(?P<format>\w+)/(?P<dat>\w+)$',
        views.chihe_stats),
    url(r'^stats/death$', views.view_death),
    url(r'^stats/death/(?P<format>\w+)/(?P<dat>\w+)$',
        views.death_stats),
    url(r'^stats/pregnancy$', views.view_pregnancy),
    url(r'^stats/risk/(?P<format>\w+)/(?P<dat>\w+)$',
        views.risk_stats),
    url(r'^stats/risk$', views.risk_details),
    url(r'^stats/pregnancy/(?P<format>\w+)/(?P<dat>\w+)$',
        views.pregnancy_stats),
    url(r'^location/(?P<pk>\d+)$', views.by_location),
    url(r'^locationcache$', views.shorthand_locations),
    url(r'^stats/agg$', views.agstats),
    url(r'^stats/aggcsv$', views.agstats_csv),
   # url(r'^batchimport/', include('batchimport.urls')),
)
